// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkCDNemnnC--Q_-iw3JSqlo9YX7fGl5mU',
    appId: '1:917278237518:web:225501f8630bd604dff41f',
    messagingSenderId: '917278237518',
    projectId: 'homhom-app',
    authDomain: 'homhom-app.firebaseapp.com',
    storageBucket: 'homhom-app.firebasestorage.app',
    measurementId: 'G-9PWF2BHF2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1vbuWkI78eOKdSqqiLNQPENw8a7DW7cI',
    appId: '1:917278237518:android:c9ed85afeda8f31fdff41f',
    messagingSenderId: '917278237518',
    projectId: 'homhom-app',
    storageBucket: 'homhom-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdTrih61uSiCVPhEl-LSYDGSg0K_6gX6k',
    appId: '1:917278237518:ios:13f744b7843743fbdff41f',
    messagingSenderId: '917278237518',
    projectId: 'homhom-app',
    storageBucket: 'homhom-app.firebasestorage.app',
    iosBundleId: 'com.saynode.homhom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdTrih61uSiCVPhEl-LSYDGSg0K_6gX6k',
    appId: '1:917278237518:ios:13f744b7843743fbdff41f',
    messagingSenderId: '917278237518',
    projectId: 'homhom-app',
    storageBucket: 'homhom-app.firebasestorage.app',
    iosBundleId: 'com.saynode.homhom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkCDNemnnC--Q_-iw3JSqlo9YX7fGl5mU',
    appId: '1:917278237518:web:d268ac1ad4618276dff41f',
    messagingSenderId: '917278237518',
    projectId: 'homhom-app',
    authDomain: 'homhom-app.firebaseapp.com',
    storageBucket: 'homhom-app.firebasestorage.app',
    measurementId: 'G-JCR5QXR87H',
  );
}
